### ISSUE TITLE
Seems to be trouble with the Poster field in the Post table

### ISSUE THREAD

**Issue by RedSkyAtMorning** [momentum-cohort-2019-02/w6-apile-team-channa#9]
![image](https://user-images.githubusercontent.com/47538213/54650811-7aedf900-4a86-11e9-90d9-bb2fc758617e.png)

**Comment by RedSkyAtMorning** [comment]
Yes, I think Foreign Keys need quotes around them like 
![image](https://user-images.githubusercontent.com/47538213/54650957-12ebe280-4a87-11e9-9283-a68d682e8145.png)

**Comment by dpeterzen** [comment]
We good now
